# -*- coding: utf-8 -*-
"""backend.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dZcNPErG7fnazSwv2k25djIXH8Ztg4Sz
"""

import tkinter as tk
import pymysql
import random

conn, cur = None, None
data1, data2, data3, data4, data5, data6 = "", "", "", "", "", ""
sql=""

conn = pymysql.connect(host='127.0.0.1', user='root', password='579579', db='db_2018102102', charset='utf8')

cur = conn.cursor()

######## drink 테이블에 데이터 추가 ########
while(True):
    # drink ID가 NULL이면 데이터 추가 취소
    print("음료 메뉴 추가를 원하지 않으시다면 Enter를 눌러주세요.")
    data1 = input("drink ID(INT) ==> ")
    if data1 == "":
        break;
    data2 = input("drink name(VARCHAR) ==> ")
    data3 = input("drink price(INT) ==> ")
    data4 = input("drink calorie(INT) ==> ")
    data5 = input("drink carbonated(CHAR) ==> ")
    data6 = input("drink discount(VARCHAR) ==> ")

    sql = "INSERT INTO drink VALUES('" + data1 + "','" + data2 + "','" + data3 + "','" + data4 + "','" + data5 + "'," + data6 + ")"
    cur.execute(sql)
conn.commit()

######## food 테이블에 데이터 추가 ########
while(True):
    # burger ID가 NULL이면 데이터 추가 취소
    print("음식 메뉴 추가를 원하지 않으시다면 Enter를 눌러주세요.")
    data1 = input("burger ID(INT) ==> ")
    if data1 == "":
        break;
    data2 = input("food name(VARHCAR) ==> ")
    data3 = input("price(INT) ==> ")
    data4 = input("calorie(INT) ==> ")
    data5 = input("vegetable(VARCHAR) ==> ")
    data6 = input("discount(VARCHAR) ==> ")

    sql = "INSERT INTO food VALUES('" + data1 + "','" + data2 + "','" + data3 + "','" + data4 + "','" + data5 + "'," + data6 + ")"
    cur.execute(sql)
conn.commit()

######## 테스트를 위한 user 테이블에 사용자 추가 ########
while(True):
    # user ID가 NULL이면 데이터 추가 취소
    print("테스트 사용자 추가를 원하지 않으시다면 Enter를 눌러주세요.")
    data1 = input("user ID(INT) ==> ")
    if data1 == "":
        print("***사용자를 위한 패스트푸드 메뉴 추천 프로그램이 켜졌습니다***")
        print("※음식 추천과 음료 추천을 모두 받고 싶으시면 음식 추천 후 화면을 닫고 다시 프로그램을 실행하여 음료 추천을 받으시길 바랍니다.")
        print("※에러 시, 추천 드릴 메뉴가 없는 것이니, 창을 닫고 다시 실행해주시길 바랍니다.")
        break;
    data2 = input("user name(VARHCAR) ==> ")
    data3 = input("phone(VARCHAR) ==> ")

    sql = "INSERT INTO user VALUES('" + data1 + "','" + data2 + "'," + data3 + ")"
    cur.execute(sql)
conn.commit()
